// @flow

import * as React from 'react';

import ImgFace from '../../assets/images/matt-turnbull-120.jpg';
import ImgFace2x from '../../assets/images/matt-turnbull-240.jpg';
import ContentA from '../../components/ContentA';
import ContentCodeBlock from '../../components/ContentCodeBlock';
import ContentH2 from '../../components/ContentH2';
import ContentH3 from '../../components/ContentH3';
import ContentImg from '../../components/ContentImg';
import ContentLI from '../../components/ContentLI';
import ContentListing from '../../components/ContentListing';
import ContentP from '../../components/ContentP';
import ContentUL from '../../components/ContentUL';
import EmailPlease from '../../components/EmailPlease';
import EmojiText from '../../components/EmojiText';
import HeadingBrick from '../../components/HeadingBrick';
import HeadTagsContent from '../../components/HeadTagsContent';
import LastUpdated from '../../components/LastUpdated';
import PageContainer from '../../components/PageContainer';
import type { Content } from '../../types/Content';
import type { Image } from '../../types/Image';
import type { Result } from '../../types/Result';
import { createImage } from '../../utils/image';
import { getResultAsArray } from '../../utils/result';
import ImgTouch from './touch.gif';

const IMG_TOUCH = createImage(ImgTouch, 480, 196);

export const frontmatter = {
	title: 'About Matt Turnbull',
	dateCreated: '2018-03-19',
	dateUpdated: '2018-03-19',
	type: 'article',
	unlisted: true,
};

declare var graphql: Function;
export const pageQuery = graphql`
	query ContentAboutQuery($slug: String!) {
		...CurrentContent
		...ContentList
		imgCrab: file(
			sourceInstanceName: { eq: "content" }
			relativePath: { eq: "about/hermit-crab.jpg" }
		) {
			childImageSharp {
				sizes(maxWidth: 580) {
					...GatsbyImageSharpSizes
				}
			}
		}
		imgCartoon: file(
			sourceInstanceName: { eq: "content" }
			relativePath: { eq: "about/cartoon.png" }
		) {
			childImageSharp {
				sizes(maxWidth: 580) {
					...GatsbyImageSharpSizes
				}
			}
		}
	}
`;

type ContentProps = {
	data: {
		currentContent: Content,
		contentListResult: Result<Content>,
		contentListNerdsResult: Result<Content>,
		imgCrab: Image,
		imgCartoon: Image,
	},
};

const ContentAbout = ({
	data: {
		currentContent,
		contentListResult,
		contentListNerdsResult,
		imgCrab,
		imgCartoon,
	},
}: ContentProps) => (
	<div>
		<HeadTagsContent content={currentContent} />
		<PageContainer small>
			<Hey />
			<ContentP>And I have a confession to make…</ContentP>
		</PageContainer>
		<PageContainer className="my-8 p-6 bg-denim-white text-center">
			<h2 className="text-xl text-denim-black">
				I love creating websites &amp; apps
			</h2>
		</PageContainer>
		<PageContainer small>
			<ContentP>
				It gets me out of bed, and keeps me up at night.
			</ContentP>

			<ContentH3 className="mt-12">Blame it on crabs</ContentH3>
			<ContentImg image={imgCrab} alt="Hermit crab" />
			<ContentP>
				It all started with building a website about hermit crabs at the
				age of 13.
			</ContentP>
			<ContentP>20 years later this passion has driven me to:</ContentP>
			<ContentUL reset className="my-6">
				<ContentLI>
					<EmojiText emoji="🛠️">
						Create great things with award-winning agencies in
						London and Melbourne
					</EmojiText>
				</ContentLI>
				<ContentLI>
					<EmojiText emoji="🤝">
						Collaborate with talented teams in Berlin, Tel Aviv, and
						Guangzhou
					</EmojiText>
				</ContentLI>
				<ContentLI>
					<EmojiText emoji="📈">
						Deliver a range of digital solutions, from prototypes
						&amp; MVPs to large-scale enterprise systems
					</EmojiText>
				</ContentLI>
			</ContentUL>

			<ContentH2>Now</ContentH2>
			{currentContent.frontmatter.dateUpdated && (
				<LastUpdated
					dateTime={currentContent.frontmatter.dateUpdated}
					className="text-xs"
				/>
			)}
			<EmojiText tag="p" emoji="📍" emojiLabel="Current location: ">
				Melbourne, Australia
			</EmojiText>
			<EmojiText tag="p" emoji="⛰" emojiLabel="Current goal: ">
				Mission for 2018: earn $2k/mo solo
			</EmojiText>
		</PageContainer>
		<PageContainer className="my-8 py-12 bg-pattern">
			<HeadingBrick>Nerds Only</HeadingBrick>
			<ContentCodeBlock
				language="markdown"
				className="bg-turtle-white py-6"
				code={`
				cat /var/log/iamturns


				# Current tech stack

				- JavaScript with static types (TypeScript / Flow)
				- React, Redux, RxJS
				- PostCSS (with SASS plugins), TailwindCSS, BEM
				- Node, GraphQL
				- AWS, Netlify

				## Previous XP

				- 7 years PHP (Laravel, Symfony, Zend Framework)
				- 3 years Angular (1.x and 2+)


				# Nerdy projects

				## This website

				- Static site generated by Gatsby, powered by React + GraphQL
				- Template built with TailwindCSS
				- Hosted on Netlify
				- View code: https://github.com/iamturns/iamturns.com

				## Configrrr

				- Angry configuration for your JS (grrr)
				- Config layering with environment variables, command line switches, and local storage
				- Code: https://github.com/turnbullm/configrrr
				- NPM: https://www.npmjs.com/package/configrrr

				## ES6 Presentation

				- Presented to AnalogFolk London development team December 2015
				- 7 reasons why ES6 matters
				- 25 best new features (with code examples + best practises)
				- How to use the features _right now_ (a bigger deal at the time)
				- View online: https://github.com/iamturns/es6-presentation/

				## JS Seed

				- Seed your JS with ES6, webpack, babel, karma, jasmine, istanbul, config, git hooks
				- Code: https://github.com/turnbullm/js-seed
			`}
			/>
		</PageContainer>
		<PageContainer small>
			<ContentImg image={imgCartoon} alt="Matt Turnbull" />

			<ContentP>Away from the keyboard I love:</ContentP>

			<ContentUL reset className="my-6">
				<ContentLI>
					<EmojiText emoji="🌏">
						<ContentA to="https://www.instagram.com/whereareweguys/">
							Exploring the world with my partner
						</ContentA>
					</EmojiText>
				</ContentLI>
				<ContentLI>
					<EmojiText emoji="🤘">
						Rocking out on drums &amp; guitar
					</EmojiText>
				</ContentLI>
				<ContentLI>
					<EmojiText emoji="📚">Learning all the things</EmojiText>
				</ContentLI>
				<ContentLI>
					<EmojiText emoji="🙃">Anything ridiculous</EmojiText>
				</ContentLI>
			</ContentUL>

			<ContentH2>Get in touch</ContentH2>

			<ContentImg image={IMG_TOUCH} type="fullwidth" />

			<ContentUL className="mt-8">
				<ContentLI className="my-4">
					<ContentA to="mailto:matt@iamturns.com">
						matt@iamturns.com
					</ContentA>
				</ContentLI>
				<ContentLI className="my-4">
					<ContentA to="https://twitter.com/iamturns">
						twitter.com/iamturns
					</ContentA>
				</ContentLI>
				<ContentLI className="my-4">
					<ContentA to="https://www.instagram.com/iamturns/">
						instagram.com/iamturns
					</ContentA>
				</ContentLI>
				<ContentLI className="my-4">
					<ContentA to="https://github.com/iamturns">
						github.com/iamturns
					</ContentA>
				</ContentLI>
				<ContentLI>
					<ContentA to="https://www.linkedin.com/in/iamturns/">
						linkedin.com/in/iamturns
					</ContentA>
				</ContentLI>
			</ContentUL>
		</PageContainer>
		<PageContainer className="mt-12 py-12 bg-denim-white">
			<EmailPlease />
		</PageContainer>
		<ContentListing
			contentList={getResultAsArray(contentListResult)}
			currentContent={currentContent}
		/>
		<ContentListing
			contentList={getResultAsArray(contentListNerdsResult)}
			currentContent={currentContent}
			nerdsOnly
		/>
	</div>
);

export default ContentAbout;

const Hey = () => (
	<div className="py-12 flex items-center justify-center">
		<div className="flex flex-col sm:flex-row items-center">
			<div className="flex-none" style={{ width: '120px' }}>
				<img
					src={ImgFace}
					srcSet={`${ImgFace2x} 2x`}
					alt="Matt Turnbull"
					width="120"
					height="120"
					className="rounded-full"
				/>
			</div>
			<div className="pt-4 sm:pt-0 sm:pl-8 text-center">
				<div className="text-lg text-turtle-darker">Hey, I’m</div>
				<h1 className="text-2xl">Matt Turnbull</h1>
			</div>
		</div>
	</div>
);
