// @flow

import * as React from 'react';

import ImgFace from '../../assets/images/matt-turnbull-120.jpg';
import ImgFace2x from '../../assets/images/matt-turnbull-240.jpg';
import CodeBlock from '../../components/CodeBlock';
import ContentListing from '../../components/ContentListing';
import EmailPlease from '../../components/EmailPlease';
import EmojiText from '../../components/EmojiText';
import HeadingBrick from '../../components/HeadingBrick';
import HeadTagsContent from '../../components/HeadTagsContent';
import ImgBlock from '../../components/ImgBlock';
import LastUpdated from '../../components/LastUpdated';
import Link from '../../components/Link';
import PageContainer from '../../components/PageContainer';
import type { Content } from '../../types/Content';
import type { Image } from '../../types/Image';
import type { Result } from '../../types/Result';
import { createImage } from '../../utils/image';
import { getResultAsArray } from '../../utils/result';
import ImgTouch from './touch.gif';

const IMG_TOUCH = createImage(ImgTouch, 480, 196);

export const frontmatter = {
	title: 'About Matt Turnbull',
	dateCreated: '2018-03-19',
	dateUpdated: '2018-03-19',
	type: 'article',
	unlisted: true,
};

declare var graphql: Function;
export const pageQuery = graphql`
	query ContentAboutQuery($slug: String!) {
		...CurrentContent
		...ContentList
		imgCrab: file(
			sourceInstanceName: { eq: "content" }
			relativePath: { eq: "about/hermit-crab.jpg" }
		) {
			childImageSharp {
				sizes(maxWidth: 580) {
					...GatsbyImageSharpSizes
				}
			}
		}
		imgCartoon: file(
			sourceInstanceName: { eq: "content" }
			relativePath: { eq: "about/cartoon.png" }
		) {
			childImageSharp {
				sizes(maxWidth: 580) {
					...GatsbyImageSharpSizes
				}
			}
		}
	}
`;

type ContentProps = {
	data: {
		currentContent: Content,
		contentListResult: Result<Content>,
		contentListNerdsResult: Result<Content>,
		imgCrab: Image,
		imgCartoon: Image,
	},
};

const ContentAbout = ({
	data: {
		currentContent,
		contentListResult,
		contentListNerdsResult,
		imgCrab,
		imgCartoon,
	},
}: ContentProps) => (
	<div>
		<HeadTagsContent content={currentContent} />
		<PageContainer small>
			<Hey />
			<p className="c-p">And I have a confession to make…</p>
		</PageContainer>
		<PageContainer className="my-8 p-6 bg-denim-white text-center">
			<h2 className="text-xl text-denim-black">
				I love creating websites &amp; apps
			</h2>
		</PageContainer>
		<PageContainer small className="wysiwyg">
			<p>It gets me out of bed, and keeps me up at night.</p>

			<h3 className="c-h3 mt-12">Blame it on crabs</h3>
			<ImgBlock image={imgCrab} alt="Hermit crab" />
			<p>
				It all started with building a website about hermit crabs at the
				age of 13.
			</p>
			<p>20 years later this passion has driven me to:</p>
			<ul className="c-list-reset my-6">
				<li>
					<EmojiText emoji="🛠️">
						Create great things with award-winning agencies in
						London and Melbourne
					</EmojiText>
				</li>
				<li>
					<EmojiText emoji="🤝">
						Collaborate with talented teams in Berlin, Tel Aviv, and
						Guangzhou
					</EmojiText>
				</li>
				<li>
					<EmojiText emoji="📈">
						Deliver a range of digital solutions, from prototypes
						&amp; MVPs to large-scale enterprise systems
					</EmojiText>
				</li>
			</ul>

			<h2>Now</h2>
			{currentContent.frontmatter.dateUpdated && (
				<LastUpdated
					dateTime={currentContent.frontmatter.dateUpdated}
					className="text-xs"
				/>
			)}
			<ul className="c-list-reset my-6">
				<li>
					<EmojiText emoji="📍" emojiLabel="Current location: ">
						Melbourne, Australia
					</EmojiText>
				</li>
				<li>
					<EmojiText emoji="⛰" emojiLabel="Current goal: ">
						Mission for 2018: earn $2k/mo solo
					</EmojiText>
				</li>
			</ul>
		</PageContainer>
		<PageContainer className="my-8 py-12 bg-pattern">
			<HeadingBrick>Nerds Only</HeadingBrick>
			<CodeBlock
				language="markdown"
				className="bg-turtle-white py-6"
				code={`
				cat /var/log/iamturns


				# Current tech stack

				- JavaScript with static types (TypeScript / Flow)
				- React, Redux, RxJS
				- PostCSS (with SASS plugins), TailwindCSS, BEM
				- Node, GraphQL
				- AWS, Netlify

				## Previous XP

				- 7 years PHP (Laravel, Symfony, Zend Framework)
				- 3 years Angular (1.x and 2+)


				# Nerdy projects


				## This website

				https://github.com/iamturns/iamturns.com

				- Static site generated by Gatsby
				  - Powered by React + GraphQL
				- Template built with TailwindCSS


				## Configrrr

				https://github.com/turnbullm/configrrr

				- Angry configuration for your JS (grrr)
				- Config layering:
				  - Environment variables
				  - Command line switches
				  - Local storage (browser)


				## ES6 Presentation

				https://github.com/iamturns/es6-presentation/

				- 7 reasons why ES6 matters
				- 25 best new features
				  - With code examples + best practises


				## JS Seed

				https://github.com/turnbullm/js-seed

				- Seed your JS
				- ES6, webpack, babel, karma, jasmine, istanbul
			`}
			/>
		</PageContainer>
		<PageContainer small className="wysiwyg">
			<ImgBlock image={imgCartoon} alt="Matt Turnbull" />

			<p>Away from the keyboard I love:</p>

			<ul className="c-list-reset">
				<li>
					<EmojiText emoji="🌏">
						<Link to="https://www.instagram.com/whereareweguys/">
							Exploring the world with my partner
						</Link>
					</EmojiText>
				</li>
				<li>
					<EmojiText emoji="🤘">
						Rocking out on drums &amp; guitar
					</EmojiText>
				</li>
				<li>
					<EmojiText emoji="📚">Learning all the things</EmojiText>
				</li>
				<li>
					<EmojiText emoji="🙃">Anything ridiculous</EmojiText>
				</li>
			</ul>

			<h2>Get in touch</h2>

			<ImgBlock image={IMG_TOUCH} type="fullwidth" />

			<ul>
				<li>
					<Link to="mailto:matt@iamturns.com">matt@iamturns.com</Link>
				</li>
				<li>
					<Link to="https://twitter.com/iamturns">
						twitter.com/iamturns
					</Link>
				</li>
				<li>
					<Link to="https://www.instagram.com/iamturns/">
						instagram.com/iamturns
					</Link>
				</li>
				<li>
					<Link to="https://github.com/iamturns">
						github.com/iamturns
					</Link>
				</li>
				<li>
					<Link to="https://www.linkedin.com/in/iamturns/">
						linkedin.com/in/iamturns
					</Link>
				</li>
			</ul>
		</PageContainer>
		<PageContainer className="mt-12 py-12 bg-denim-white">
			<EmailPlease />
		</PageContainer>
		<ContentListing
			contentList={getResultAsArray(contentListResult)}
			currentContent={currentContent}
		/>
		<ContentListing
			contentList={getResultAsArray(contentListNerdsResult)}
			currentContent={currentContent}
			nerdsOnly
		/>
	</div>
);

export default ContentAbout;

const Hey = () => (
	<div className="py-12 flex items-center justify-center">
		<div className="flex flex-col sm:flex-row items-center">
			<div className="flex-none" style={{ width: '120px' }}>
				<img
					src={ImgFace}
					srcSet={`${ImgFace2x} 2x`}
					alt="Matt Turnbull"
					width="120"
					height="120"
					className="rounded-full"
				/>
			</div>
			<div className="pt-4 sm:pt-0 sm:pl-8 text-center">
				<div className="text-lg text-turtle-darker">Hey, I’m</div>
				<h1 className="text-2xl">Matt Turnbull</h1>
			</div>
		</div>
	</div>
);
